# Generated by Django 3.0.2 on 2020-02-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200129_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('passanger_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('passanger_name', models.CharField(max_length=250)),
                ('passport_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticket_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=3)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Flights_details')),
                ('passanger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Passanger')),
            ],
        ),
    ]
