# Generated by Django 3.0.2 on 2020-02-08 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_passanger'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 19, 26, 8, 232523), verbose_name='date published'),
        ),
    ]
