# Generated by Django 3.0.2 on 2020-02-14 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20200211_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 18, 4, 2, 881831), verbose_name='date published'),
        ),
    ]
